import { createOptimizedPicture } from '../../scripts/aem.js';

/*
 * Article List Block
 *
 * Renders a dynamic list of published pages sourced from the site's query
 * index (query-index.json). Because the index is regenerated by the backend
 * whenever a page is published, publishing a new page makes it appear in this
 * list automatically — no code or content change required.
 *
 * Content model (all optional):
 *   Row 1: a link to the index JSON (defaults to /query-index.json)
 *   Row 2: a path prefix to filter results (e.g. /blog/), so the same block
 *          can power different listings
 *   Row 3: a numeric limit on how many articles to show
 *
 * Authors who want a plain listing of every published page can leave the
 * block empty.
 */

const DEFAULT_SOURCE = '/query-index.json';

/**
 * Reads block configuration from its rows without assuming a fixed order.
 * @param {Element} block the block element
 * @returns {{source: string, filter: string, limit: number}}
 */
function readConfig(block) {
  const config = { source: DEFAULT_SOURCE, filter: '', limit: 0 };

  const link = block.querySelector('a[href]');
  if (link) config.source = link.getAttribute('href');

  [...block.children].forEach((row) => {
    if (row.querySelector('a[href]')) return;
    const text = row.textContent.trim();
    if (!text) return;
    if (/^\d+$/.test(text)) {
      config.limit = parseInt(text, 10);
    } else if (text.startsWith('/')) {
      config.filter = text;
    } else if (text.startsWith('http')) {
      config.source = text;
    }
  });

  return config;
}

/**
 * Fetches the index rows from the query index JSON.
 * @param {string} source the index JSON path/URL
 * @returns {Promise<Array<Object>>} array of page records
 */
async function fetchIndex(source) {
  try {
    const resp = await fetch(source);
    if (!resp.ok) throw new Error(`Failed to load index: ${resp.status}`);
    const json = await resp.json();
    return json.data || [];
  } catch {
    return [];
  }
}

/**
 * Builds a single article card.
 * @param {Object} page a page record from the index
 * @returns {HTMLElement} the list item element
 */
function buildCard(page) {
  const li = document.createElement('li');
  li.className = 'article-list-card';

  const link = document.createElement('a');
  link.className = 'article-list-link';
  link.href = page.path;

  if (page.image) {
    const imageWrap = document.createElement('div');
    imageWrap.className = 'article-list-card-image';
    imageWrap.append(
      createOptimizedPicture(page.image, page.title || '', false, [{ width: '750' }]),
    );
    link.append(imageWrap);
  }

  const body = document.createElement('div');
  body.className = 'article-list-card-body';

  if (page.title) {
    const title = document.createElement('h3');
    title.className = 'article-list-card-title';
    title.textContent = page.title;
    body.append(title);
  }

  if (page.description) {
    const desc = document.createElement('p');
    desc.className = 'article-list-card-description';
    desc.textContent = page.description;
    body.append(desc);
  }

  link.append(body);
  li.append(link);
  return li;
}

export default async function decorate(block) {
  const { source, filter, limit } = readConfig(block);
  const rows = await fetchIndex(source);

  let articles = rows;
  if (filter) articles = articles.filter((row) => row.path?.startsWith(filter));
  if (limit > 0) articles = articles.slice(0, limit);

  block.textContent = '';

  if (articles.length === 0) {
    const empty = document.createElement('p');
    empty.className = 'article-list-empty';
    empty.textContent = 'No articles found.';
    block.append(empty);
    return;
  }

  const ul = document.createElement('ul');
  ul.className = 'article-list-items';
  articles.forEach((page) => ul.append(buildCard(page)));
  block.append(ul);
}
